version: '3.8'
volumes:
  data:
  cache:

services:
  cache:
    image: redis:latest
    command: redis-server --save 20 1 --loglevel warning --requirepass 95da0b09179d6ee9
    volumes:
      - data:/data